apiVersion: apps/v1
kind: Deployment
metadata:
   name: eksdemo
spec:
   replicas: 2
   selector:
      matchLabels:
         app: eksdemo
   minReadySeconds: 10
   strategy:
      type: RollingUpdate
      rollingUpdate:
         maxUnavailable: 1
         maxSurge: 1
   template:
      metadata:
         labels:
            app: eksdemo
      spec:
         containers:
         - name: eksdemo
           image: tilakkalyan/eksdemo
           ports:
           - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: eksdemo
spec:
  type: NodePort
  selector:
    app: eksdemo
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30011
      
      